# 📊 Proyecto: Análisis Comercial Inmobiliario

El sector inmobiliario necesita evaluar su **desempeño comercial** para comprender su crecimiento, rentabilidad y comportamiento de clientes.

Se solicita construir un **dashboard ejecutivo** que permita analizar ventas, clientes y propiedades para apoyar decisiones estratégicas basadas en datos.

In [1]:
import os
os.listdir()

['S11 Estudiante_Proyecto_InmobiliarioGrupoAndes.ipynb',
 'hecho_ventas_propiedades(3).csv',
 'dim_clientes(1).csv',
 '.ipynb_checkpoints',
 'Untitled Folder',
 'dim_propiedades.csv']

In [2]:
import pandas as pd

df_ventas = pd.read_csv('hecho_ventas_propiedades(3).csv')
df_clientes = pd.read_csv('dim_clientes(1).csv')
df_propiedades = pd.read_csv('dim_propiedades.csv')

df_ventas.head()

,id_venta,fecha_venta,id_cliente,id_propiedad,ciudad,precio_venta,tipo_propiedad,canal_venta,porcentaje_comision,monto_comision
0,SALE000001,1/5/2024,CUST02497,PROP03591,Bogotá,1027126,Casa,Corredor,0.0473,48605
1,SALE000002,6/16/2024,CUST02903,PROP03005,Ciudad de México,233363,Departamento,Corredor,0.0458,10681
2,SALE000003,10/13/2024,CUST00831,PROP04661,Bogotá,209704,Departamento,Directo,0.0151,3156
3,SALE000004,2/8/2023,CUST01686,PROP06300,Bogotá,224411,Departamento,Corredor,0.0380,8523
4,SALE000005,11/29/2024,CUST00639,PROP00792,Ciudad de México,192007,Departamento,Directo,0.0159,3054

# 📂 Descripción de los Datasets

🔹 **hecho_ventas_propiedades**  
Tabla de hechos con las transacciones de venta (precio, cliente, propiedad, canal, fecha).

🔹 **dim_clientes**  
Información y segmentación de clientes.

🔹 **dim_propiedades**  
Características de las propiedades (tipo, tamaño, ubicación, etc).

🔹 **dim_fecha**  
Tabla calendario que deberá ser creada como parte del modelado.

# 🎯 Preguntas que el dashboard debe responder

**Desempeño general**

- ¿Cuál es el **ingreso total** generado por la empresa?- 
- ¿Cuántas **propiedades se han vendido**?
- ¿Cuál es el **precio promedio de venta**?
- ¿Cuál es la **comisión total** generada por la empresa?

**Análisis comercial**

- ¿Qué **tipo de propiedad genera más ingresos**?
- ¿Qué **segmento de clientes compra más propiedades**?
- ¿Qué canal de venta **genera mayor ingresos**?


**Análisis temporal**

- ¿Cómo evolucionan las **ventas en el tiempo**?
- ¿El negocio está **creciendo año contra año**?
- ¿Cómo va el desempeño **acumulado del año actual (YTD)**?

**Cohortes de clientes**

- ¿Los clientes **vuelven a comprar** después de su primera compra?
- ¿Qué **cohortes de clientes generan más compras/ingresos con el tiempo**?

Desempeño general

    ¿Cuál es el ingreso total generado por la empresa?
  El ingreso total generado por la empresa, calculado como la suma de todas las transacciones de venta registradas, asciende aproximadamente a 6 mil millones durante el periodo analizado. Este resultado corresponde al desempeño comercial comprendido entre los años 2023 y 2024, lo que permite dimensionar el tamaño del negocio y su capacidad de generación de ingresos en dicho intervalo de tiempo.

    ¿Cuántas propiedades se han vendido?
  El número total de propiedades vendidas, calculado a partir de las transacciones registradas, asciende a aproximadamente 8500 propiedades, lo que evidencia un volumen significativo de operaciones y una alta actividad comercial durante el periodo analizado.
   
    ¿Cuál es el precio promedio de venta?
  El precio promedio de venta se obtiene a partir del promedio de los valores de todas las transacciones registradas. De acuerdo con el dashboard, el precio promedio de las propiedades vendidas es de aproximadamente 707.35 mil durante el periodo comprendido entre 2023 y 2024, lo que permite identificar el valor medio de mercado en el que se están realizando las operaciones.
  
    ¿Cuál es la comisión total generada por la empresa?
  La comisión total generada por la empresa corresponde a la suma de las comisiones obtenidas en todas las transacciones de venta realizadas. De acuerdo con el dashboard, la comisión total asciende aproximadamente a 201 millones durante el periodo comprendido entre 2023 y 2024, lo que refleja los ingresos derivados de la intermediación en las operaciones inmobiliarias.
  

Análisis comercial

    ¿Qué tipo de propiedad genera más ingresos?
  El análisis por tipo de propiedad muestra que las casas son el segmento que genera mayores ingresos, alcanzando aproximadamente 2.2 mil millones durante el periodo 2023–2024. Este valor supera a los ingresos generados por propiedades comerciales y departamentos, lo que indica que las casas representan el principal motor de ingresos dentro del portafolio inmobiliario.
    
    ¿Qué segmento de clientes compra más propiedades?
  Para identificar qué segmento de clientes compra más propiedades, se construyó en Power BI un gráfico de barras utilizando el campo segmento_comprador en el eje y la medida Propiedades Vendidas en valores. Al ordenar los resultados de forma descendente, se observa que el segmento Primera vez es el que registra el mayor volumen de compras, con aproximadamente 5.3 mil propiedades vendidas durante el periodo analizado. Esto indica que los compradores de primera vez representan el principal motor de demanda dentro del negocio inmobiliario.
    
    ¿Qué canal de venta genera mayor ingresos?
  Para identificar el canal de venta con mayor generación de ingresos, se construyó en Power BI un gráfico de barras utilizando el campo canal_venta en el eje y la medida Ingresos Totales como valor.

  El análisis muestra que el canal Corredor es el que genera mayores ingresos, con aproximadamente 4.4 mil millones durante el periodo 2023–2024, superando ampliamente al canal directo con 1.4 mil millones. Esto indica que la intermediación a través de corredores es el medio más efectivo para la comercialización de propiedades y representa un componente clave en la estrategia comercial de la empresa.
  

Análisis temporal

    ¿Cómo evolucionan las ventas en el tiempo?
  Para analizar la evolución de las ventas en el tiempo, se construyó en Power BI un gráfico de línea utilizando la fecha como eje y la medida Ingresos YTD (Year To Date) como valor, lo que permite observar el comportamiento acumulado de los ingresos a lo largo de los años 2023 y 2024.

  El análisis muestra que las ventas presentan un crecimiento progresivo dentro de cada año, acumulándose de manera constante. En 2023 se observa un incremento sostenido hasta alcanzar aproximadamente entre 2.5 y 3 mil millones, mientras que en 2024 el crecimiento es más acelerado, alcanzando niveles superiores a los del año anterior. Esto indica una mejora en el desempeño del negocio en el periodo más reciente y una tendencia positiva en la generación de ingresos.
  
    ¿El negocio está creciendo año contra año?
  Para evaluar si el negocio está creciendo año contra año, se construyó en Power BI un gráfico de líneas comparando los ingresos mensuales por año, utilizando el mes como eje y el año como leyenda, junto con un indicador clave de desempeño (YoY %).

  El análisis muestra que el negocio presenta un crecimiento positivo en el periodo más reciente, ya que los ingresos del año 2024 superan en varios meses a los de 2023. Esto se confirma con el indicador YoY %, que muestra un crecimiento aproximado del 111%, evidenciando una mejora significativa en el desempeño del negocio año contra año.
    
    ¿Cómo va el desempeño acumulado del año actual (YTD)?
  Para evaluar el desempeño acumulado del año actual, se utilizó en Power BI un gráfico de línea con la medida Ingresos YTD (Year To Date), que permite observar la acumulación progresiva de ingresos a lo largo del tiempo.

  El análisis muestra que el desempeño del año actual presenta un crecimiento sostenido, acumulando aproximadamente 3 mil millones en ingresos. La tendencia es claramente ascendente a lo largo del año, lo que indica una generación constante de ingresos y un desempeño positivo del negocio en el periodo más reciente.



Cohortes de clientes

    ¿Los clientes vuelven a comprar después de su primera compra?
  El análisis de cohortes evidencia que las cohortes más antiguas, en particular la de enero de 2023, concentran la mayor generación de ingresos a lo largo del tiempo. Esto sugiere que los clientes adquiridos en etapas tempranas no solo tienen mayor antigüedad, sino también un comportamiento de recompra más prolongado, lo que incrementa su valor acumulado. Por el contrario, las cohortes más recientes aún no alcanzan niveles similares, debido a su menor tiempo de exposición en el ciclo de vida del cliente.

    ¿Qué cohortes de clientes generan más compras/ingresos con el tiempo?
  El análisis de cohortes evidencia que las cohortes iniciales, particularmente la de enero de 2023, concentran la mayor generación de ingresos en el tiempo. Esto sugiere que los clientes adquiridos en etapas tempranas no solo generan un mayor valor inicial, sino que también presentan un comportamiento de recompra más prolongado, incrementando su valor acumulado. Las cohortes más recientes aún no alcanzan estos niveles debido a su menor madurez dentro del ciclo de vida del cliente.

## 🧹 Paso 1: Limpieza de datos

Antes del modelado, debes validar y depurar la información.

### Tipos de datos

- `fecha_venta` debe estar en formato **Date**.
- Los campos numéricos deben estar correctamente formateados.
- `porcentaje_comision` debe estar en formato **porcentaje**.

### Valores nulos

- Revisar valores **nulos** en las tablas.
- Justificar si deben eliminarse o mantenerse.

### Duplicados

- Validar que no existan duplicados en las claves primarias de:
  - `dim_clientes`
  - `dim_propiedades`

### 📝 Feedback del evaluador

_El evaluador escribirá aquí sus comentarios en caso de ser necesario._

In [3]:
df_ventas.info()
df_clientes.info()
df_propiedades.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8500 entries, 0 to 8499
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_venta             8500 non-null   object
 1   fecha_venta          8500 non-null   object
 2   id_cliente           8500 non-null   object
 3   id_propiedad         8500 non-null   object
 4   ciudad               8500 non-null   object
 5   precio_venta         8500 non-null   int64
 6   tipo_propiedad       8500 non-null   object
 7   canal_venta          8500 non-null   object
 8   porcentaje_comision  8500 non-null   float64
 9   monto_comision       8500 non-null   int64
dtypes: float64(1), int64(2), object(7)
memory usage: 664.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_cliente          3500 non-null   object
 1   segmento_comprador  3500 non-null   object
 2   pais                3500 non-null   object
 3   ciudad              3500 non-null   object
dtypes: object(4)
memory usage: 109.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_propiedad         8000 non-null   object
 1   tipo_propiedad       8000 non-null   object
 2   ciudad               8000 non-null   object
 3   barrio               8000 non-null   object
 4   habitaciones         8000 non-null   int64
 5   tamano_m2            8000 non-null   int64
 6   precio_publicado     8000 non-null   int64
 7   categoria_propiedad  8000 non-null   object
dtypes: int64(3), object(5)
memory usage: 500.1+ KB

In [4]:
df_propiedades.describe()

       habitaciones    tamano_m2  precio_publicado
count   8000.000000  8000.000000      8.000000e+03
mean       2.339375   179.553500      7.608052e+05
std        1.366723   113.267421      6.901234e+05
min        0.000000    45.000000      8.554800e+04
25%        2.000000    99.000000      3.304380e+05
50%        2.000000   146.000000      5.266295e+05
75%        3.000000   232.000000      9.289555e+05
max        6.000000   599.000000      5.206092e+06

In [5]:
df_ventas.isna().sum()
df_clientes.isna().sum()
df_propiedades.isna().sum()

id_propiedad           0
tipo_propiedad         0
ciudad                 0
barrio                 0
habitaciones           0
tamano_m2              0
precio_publicado       0
categoria_propiedad    0
dtype: int64

## 📅 Paso 2: Creación de tabla calendario

Si vas a realizar el dashboard en **Power BI**, deberás crear una tabla calendario llamada **dim_fecha**.

**Requisitos (solo para Power BI):**

- Utilizar las funciones `CALENDAR` y `ADDCOLUMNS`.
- El rango de fechas debe construirse dinámicamente desde la **fecha mínima** hasta la **fecha máxima** de ventas en `hecho_ventas_propiedades`.
- Incluir como mínimo las siguientes columnas:
  - Año
  - Mes (nombre)
  - Número de mes
  - Año-Mes (formato `YYYY-MM`)

> ⚠️ **Nota:**  
> Si utilizas **Tableau**, no necesitas crear esta tabla. Puedes usar directamente el campo `fecha_venta` de la tabla `hecho_ventas_propiedades`, ya que Tableau genera automáticamente las jerarquías de fecha.

### 📝 Feedback del evaluador

_El evaluador escribirá aquí sus comentarios en caso de ser necesario._

## 🧩 Paso 3: Modelado de datos

### Modelo requerido: Esquema estrella

El modelo debe estructurarse en formato estrella:

- `hecho_ventas_propiedades` como tabla central.
- Tablas dimensionales conectadas:
  - `dim_clientes`
  - `dim_propiedades`
  - `dim_fecha` (creada por ti, en caso de que aplique)

Requisitos de las relaciones:

- Cardinalidad **uno a muchos (1:*)**
- Dirección de filtro **simple (single)**
- Relaciones basadas en las claves correctas
- Todas las relaciones deben estar **activas**

### 📝 Feedback del evaluador

_El evaluador escribirá aquí sus comentarios en caso de ser necesario._

## 📊 Paso 4: Creación de medidas

En este paso deberás crear las **medidas necesarias para responder las preguntas de negocio del dashboard**.

Las medidas pueden implementarse en **Power BI (DAX)** o como **Calculated Fields en Tableau**.

---

### 4.1 🔹 Medidas base

Crear como mínimo las siguientes medidas:

- **Ingreso Total** (suma del `precio_venta`)
- **Cantidad de Ventas**
- **Ticket Promedio**
- **Comisión Total**

Estas métricas permitirán analizar el desempeño general del negocio.

---

### 4.2 🔹 Medidas con contexto de filtro

Debes crear **al menos 2 medidas** que modifiquen el contexto de filtro.

En este caso se utilizarán **medidas de participación (%)**, que permiten entender **qué proporción del ingreso total aporta cada categoría**.

Las medidas que deben construirse son:

- **Participación de ingresos por tipo de propiedad**
- **Participación de ingresos por canal de venta**
- **Participación de ingresos por segmento de cliente**

Para ello:
- Modifica el contexto de filtro con las funciones propias de cada herramienta
  - En Power BI, usa `CALCULATE`
  - En Tableau, usa expresiones como `FIXED` (LOD)

Elimina el filtro de la dimensión correspondiente para obtener el total

Asegúrate de que el denominador represente el total sin el filtro de la categoría, mientras que el numerador sí lo conserva.

Estas medidas se utilizarán principalmente como **tooltip o etiqueta adicional en los gráficos** del dashboard para complementar el análisis.

---

### 4.3 🔹 Inteligencia de tiempo

Utilizando la tabla **`dim_fecha`** (Power BI) o las funciones de fecha en Tableau, debes crear al menos 2 de las siguientes medidas:

- **Ventas Year to Date (YTD)**
- **Ventas Month to Date (MTD)**
- **Ventas del año anterior**
- **Crecimiento Year over Year (YoY)**

Estas métricas permitirán analizar la evolución del negocio en el tiempo.

---

### 4.4 🔹 Medidas para análisis de cohortes

Debes crear cálculos que permitan analizar **si los clientes vuelven a comprar después de su primera compra**.

⚠️ Estos cálculos deben crearse como **columnas calculadas**, no como medidas.  
Todas deben crearse en la tabla **`hecho_ventas_propiedades`**.

Debes crear como mínimo:

- **Primera compra por cliente** → fecha mínima de compra de cada cliente.
- **Mes Cohorte** → mes en que el cliente realizó su **primera compra** (mes de adquisición).
- **Mes Venta** → mes en que ocurre cada transacción. Este campo permite identificar **cuándo el cliente vuelve a comprar** después de su primera compra.

Estos cálculos permitirán construir una **matriz de cohortes** donde:

- **Filas** representen el **mes de cohorte**
- **Columnas** representen el **mes de venta**
- **Valores** muestren **cantidad de ventas o ingresos**

---

### 📝 Feedback del evaluador

_El evaluador escribirá aquí sus comentarios en caso de ser necesario._

## 📊 Paso 5: Estructura del reporte

El dashboard debe contener **mínimo tres páginas**.

---

### 5.1 1️⃣ Overview Ejecutivo

Debe mostrar **el desempeño general del negocio**.

Incluir minimo 4 KPIs:

- **KPIs principales**  
  - Ingreso Total  
  - Cantidad de Ventas  
  - Ticket Promedio  
  - Comisión Total  

- **Tendencia de ventas en el tiempo**

- **Ingresos o ventas por ciudad**

- **Crecimiento Year over Year (YoY)**

---

### 5.2 2️⃣ Análisis Comercial

Debe analizar **qué productos, canales y clientes generan más ingresos**.

Incluir:

- **Ingreso por tipo de propiedad**
- **Ventas o ingresos por canal de venta**
- **Ventas o ingresos por segmento de cliente**
- **Tabla con formato condicional (colores semáforo)**  
  Sugerencia de campos:
  - tipo_propiedad
  - Ingreso Total
  - Cantidad Ventas
  - Ticket Promedio  
  Aplicar **formato condicional** para resaltar las categorías con mayor desempeño.

Se recomienda usar **tooltips con medidas de participación (%)**.

---

### 5.3 3️⃣ Análisis de Cohortes

Debe analizar **recurrencia de clientes**.

Incluir:

- **Matriz de cohortes**
  - Filas → Mes Cohorte
  - Columnas → Mes Venta
  - Valores → Cantidad Ventas o Ingreso Total

Esto permitirá observar **si los clientes vuelven a comprar y comparar cohortes en el tiempo**.

Para analizar la recurrencia de clientes, se construyó una matriz de cohortes en Power BI utilizando la tabla de ventas.

La estructura de la matriz es la siguiente:

Filas: Mes de Cohorte (mes de la primera compra del cliente)
Columnas: Mes de Venta (momento en que ocurre cada transacción)
Valores: Ingresos Totales

Esta visualización permite observar el comportamiento de los clientes a lo largo del tiempo después de su primera compra, identificando patrones de recompra.

El análisis muestra que los clientes continúan generando ingresos en meses posteriores a su adquisición, lo que indica la existencia de recurrencia y una adecuada retención. Además, permite comparar el desempeño de diferentes cohortes y evaluar cuáles generan mayor valor a lo largo del tiempo.

### 📝 Feedback del evaluador

_El evaluador escribirá aquí sus comentarios en caso de ser necesario._

## 📝Paso 6:  Resumen Ejecutivo

Escribe aquí un resumen con:

- hallazgos clave
- métricas principales
- insights accionables
- recomendaciones estratégicas

Ejemplos:

**Hallazgos clave**
- El ingreso total del periodo fue de $X generado por X ventas.
- El tipo de propiedad que genera mayor revenue es ______.
- La ciudad con mayor volumen de ventas es ______.
- El canal de venta más eficiente en términos de ingresos es ______.

**Métricas principales**
- Ingreso Total: X
- Cantidad de Ventas: X 
- Ticket Promedio:  X 
- Comisión Total:  X 

**Insights accionables**
- El segmento de clientes ______ concentra la mayor parte del ingreso.
- Los clientes adquiridos en las cohortes de ______ muestran mayor recurrencia.
- Las ventas muestran un crecimiento/disminución de X% YoY.

**Recomendaciones estratégicas**
- Priorizar la comercialización de propiedades tipo ______.
- Fortalecer el canal de ventas ______ que presenta mayor participación en el revenue.
- Implementar estrategias de retención para mejorar la recompra en cohortes recientes.

Hallazgos clave

- El ingreso total del periodo fue de 6,013 millones, generado por 8,500 ventas.
- El tipo de propiedad que genera mayor revenue es Casa.
- La ciudad con mayor volumen de ventas es Ciudad de México.
- El canal de venta más eficiente en términos de ingresos es Corredor.

Métricas principales

- Ingreso Total: 6,013 millones
- Cantidad de Ventas: 8,500
- Ticket Promedio: 707.35 mil
- Comisión Total: 201 millones

Insights accionables

- El segmento de clientes Primera vez concentra la mayor parte del ingreso.
- Los clientes adquiridos en las cohortes de enero 2023 muestran mayor recurrencia.
- Las ventas muestran un crecimiento de aproximadamente 111% YoY.

Recomendaciones estratégicas

- Priorizar la comercialización de propiedades tipo Casa.
- Fortalecer el canal de ventas Corredor que presenta mayor participación en el revenue.
- Implementar estrategias de retención para mejorar la recompra en cohortes recientes.

Durante el periodo comprendido entre 2023 y 2024, la empresa alcanzó un ingreso total aproximado de 6,013 millones, generado a partir de 8,500 transacciones, lo que refleja un volumen operativo elevado y una capacidad sólida de generación de ingresos. Este desempeño indica una actividad comercial constante y un mercado con buena absorción de propiedades.

Al analizar la composición de los ingresos por tipo de propiedad, se observa que las casas representan el segmento más relevante, concentrando la mayor proporción del revenue total. Este comportamiento sugiere que este tipo de propiedad no solo tiene una mayor demanda, sino posiblemente un ticket promedio más alto en comparación con otras categorías como departamentos o propiedades comerciales.

Desde una perspectiva geográfica, la Ciudad de México destaca como el principal mercado en términos de generación de ingresos, superando a otras ciudades analizadas. Esto indica una alta concentración de actividad económica y oportunidades comerciales en esta región, posicionándola como un punto estratégico clave para el negocio.

En cuanto a los canales de venta, el canal de corredores se consolida como el más eficiente, al generar la mayor proporción de ingresos. Esto sugiere que la intermediación profesional juega un papel fundamental en el cierre de operaciones, posiblemente debido a una mayor capacidad de negociación, alcance de clientes o especialización en el mercado inmobiliario.

Adicionalmente, el análisis del comportamiento de los clientes muestra que el segmento de compradores de primera vez es el que concentra la mayor cantidad de transacciones, lo que indica una fuerte entrada de nuevos clientes al mercado. Esto representa una oportunidad importante para desarrollar estrategias de fidelización y aumentar el valor de vida del cliente.

Finalmente, el análisis temporal evidencia una tendencia de crecimiento positiva, con un incremento significativo en el desempeño del año 2024 respecto a 2023, respaldado por el indicador YoY. A su vez, el análisis de cohortes confirma que los clientes continúan realizando compras en periodos posteriores a su adquisición inicial, lo que indica un comportamiento de recompra y una adecuada retención dentro del negocio.

### 📝 Feedback del evaluador

_El evaluador escribirá aquí sus comentarios._

## 🚀 Entrega Final

Comparte el acceso a tu proyecto final para revisión.

Puedes entregar el proyecto utilizando **Power BI o Tableau**.

Incluye **uno de los siguientes**:

- 🔗 Link público del dashboard publicado en **Power BI Service o Tableau Public / Tableau Cloud**
- 🔗 Link de **Google Drive o OneDrive** con el archivo `.pbix` del proyecto
- ✅ Confirmación de que el archivo `.pbix` fue subido según las instrucciones del curso

### 📎 Enlace del proyecto
✏️ (Pega aquí tu link o escribe "Subi mi proyecto a la plataforma")

In [6]:
https://drive.google.com/file/d/1z2z4Q-JqFI3cWY0Eb6wXDxzxDBK4lDvk/view?usp=sharing

<div class="alert alert-block alert-success">
<b>Comentario del revisor</b> <a class="tocSkip"></a><br><br>

Hola, Julieta. Realizaste un excelente trabajo.<br><br> <b>Éxito.</b> El proyecto cumple con lo solicitado: el dashboard es funcional, coherente y comunica hallazgos accionables con datos bien preparados. Además, la estructura permite responder claramente las preguntas clave del negocio (desempeño general, análisis comercial, análisis temporal y cohortes).<br><br> <b>1) Planificación y diseño (enfoque en las preguntas del dashboard)</b><br> ✅ Los KPIs seleccionados están alineados con los objetivos: ingreso total, propiedades vendidas, precio promedio y comisión total. La secuencia del dashboard facilita responder preguntas comerciales (tipo de propiedad, segmento de clientes, canal) y temporales (tendencia, YoY y YTD).<br><br> <b>2) Resumen ejecutivo (Paso 6)</b><br> ✅ El resumen se presenta de forma clara y accionable: incluye hallazgos clave, métricas principales, insights y recomendaciones estratégicas. Esto es muy valioso porque traduce el dashboard en decisiones concretas (qué priorizar, qué canal potenciar y dónde enfocar retención).<br><br> <b>3) Análisis e insights</b><br> ✅ Identificas patrones relevantes (tendencias, segmentos y comparaciones) y los conectas con lógica de negocio. Los insights están respaldados por la evidencia mostrada en el dashboard, especialmente en desempeño comercial y evolución temporal.<br><br> <b>4) Visualización y diseño del dashboard</b><br> ✅ Diseño limpio y legible, con jerarquía visual adecuada, títulos informativos y filtros útiles. Las visualizaciones elegidas ayudan a responder: evolución en el tiempo, comparaciones por geografía/estación, detalle de ventas y desempeño por canal/segmento.<br><br> <b>5) Interactividad y usabilidad</b><br> ✅ Navegación intuitiva; los filtros responden como se espera y permiten segmentar por dimensiones clave. Las pestañas ayudan al usuario a llegar a conclusiones sin perder el hilo del análisis.<br><br> <b>6) Reproducibilidad y buenas prácticas</b><br> ✅ Proceso ordenado y replicable (carga → limpieza → análisis → visualización), con nombres consistentes y pasos claros.<br><br> <b>Sugerencia de mejora:</b> En futuras versiones, podrías explorar sincronizar filtros entre pestañas y enriquecer el análisis estacional (por ejemplo, comparaciones más explícitas por estación y su impacto en ventas).

<b>Puntos especificos</b><br> 

✅ Excelente trabajo con el Overview: puedes complementar colocando el filtro del año,  país, segmento e ingresos por tipo de propiedad para hacer más dinamico el tablero. Colocas perfectamente las tarjetas con als variables de Ingreso total, cantidad de ventas. Esto puedes complementarlo con el 
ticket promedio, comisión total y porcentaje de comisión. Además complementas con gráficas de la serie con las ventas 

✅ Pestaña de Análisis comercial: Mantienes los filtros anteriores (pudieramos explorar relacionarlo con las otras pestañas) pero complementas con gráficas de ingresos por propiedad, venta y cliente

✅ Mapa de calor para mostrar la retención por cliente y cohorte

Al final complementas con pestañas adicionales para el análisis de variables especificas

<br><br> <b>Resultado:</b> Proyecto aprobado. Excelente trabajo. </div> ```